{% set name = "virtualenv-clone" %}
{% set version = "0.5.5" %}
{% set sha256 = "fa23525c4fcc7ff91248beeee53317dd6ac5e74c0e5c66c1807c1b0b7d948ab6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - virtualenv-clone=clonevirtualenv:main

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  commands:
    - virtualenv-clone --help

about:
  home: https://github.com/edwardgeorge/virtualenv-clone/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: script to clone virtualenvs.
  description: |
    A script for cloning a non-relocatable virtualenv.
  doc_url: https://github.com/edwardgeorge/virtualenv-clone/
  dev_url: https://github.com/edwardgeorge/virtualenv-clone/

extra:
  recipe-maintainers:
    - holgern
